llama2-7b:
  model_id: "meta-llama/Llama-2-7b"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer:"
  flash_attention2: "true"
  gradient_checkpointing: "true"
  ga_lr: "1e-5"
  ga_num_epochs: 16
  npo_lr: "2e-5"
  npo_num_epochs: 16
  whp_alpha_list: "0.5 1.0 5.0 10.0 100.0 1000.0"
  tv_alpha_list: "0.2 0.5 1.0 5.0 10.0"
  reinforce_lr: "1e-5"
llama3-8b:
  model_id: "meta-llama/Meta-Llama-3-8B"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer:"
  flash_attention2: "true"
  gradient_checkpointing: "true"
  ga_lr: "1e-5"
  ga_num_epochs: 16
  npo_lr: "2e-5"
  npo_num_epochs: 16
  whp_alpha_list: "0.5 1.0 5.0 10.0 100.0 1000.0"
  tv_alpha_list: "0.2 0.5 1.0 5.0 10.0"
  reinforce_lr: "1e-5"
gpt2-xl:
  model_id: "openai-community/gpt2-xl"
  question_start_tag: "Question: "
  question_end_tag: "\n Answer:"
  answer_tag: ""
  flash_attention2: "true"
  gradient_checkpointing: "true"
  ga_lr: "2e-5"
  ga_num_epochs: 32
  npo_lr: "4e-5"
  npo_num_epochs: 32
  whp_alpha_list: "0.5 1.0 5.0 10.0 100.0 1000.0"
  tv_alpha_list: "0.2 1.0 5.0 10.0 30.0 60.0 80.0"
  reinforce_lr: "2e-5"
phi:
  model_id: "microsoft/phi-1_5"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
  ga_lr: "2e-5"
  ga_num_epochs: 16
  npo_lr: "4e-5"
  npo_num_epochs: 16
  whp_alpha_list: "0.5 1.0 5.0 10.0 100.0 1000.0"
  tv_alpha_list: "0.2 0.5 1.0 5.0 10.0"
  reinforce_lr: "2e-5"